#version: "3"
services:
  # postgres:
  #   image: "postgres:latest"
  #   environment:
  #     POSTGRES_USER: "admin"
  #     POSTGRES_PASSWORD: "admin"
  #     POSTGRES_DB: "matrix"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - "postgres:/var/lib/postgresql/data"
  web:
    command: npm run start
    ports:
      - "80:3000"
    restart: always
    build: .

volumes:
  postgres:
    driver: local

