#version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "matrix"
    ports:
      - "5433:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
    driver: local

